import { useDispatch, useSelector } from "react-redux";
import {
  toggleAssistant,
  addMessage,
  setAssistantStatus,
} from "../../store/assistantSlice";

import {
  updateCandidateStage,
  updateRubric,
  addAuditLog,
} from "../../store/recruiterSlice";

import AssistantAvatar from "./AssistantAvatar";

export default function AssistantPanel() {
  const dispatch = useDispatch();

  const assistant = useSelector((state) => state.assistant);
  const jobs = useSelector((state) => state.recruiter.jobs);

  if (!assistant.isOpen) return null;

  const sendMessage = (text) => {
    if (!text.trim()) return;

    dispatch(
      addMessage({
        sender: "user",
        text,
        time: new Date().toLocaleTimeString(),
      })
    );

    dispatch(setAssistantStatus("thinking"));

    setTimeout(() => {
      handleCommand(text.toLowerCase());
    }, 700);
  };

  const handleCommand = (text) => {
    const job = jobs[0]; // demo purpose

    // 1️⃣ Generate Rubric
    if (text.includes("generate")) {
      dispatch(
        updateRubric({
          jobId: job.id,
          rubric: [
            { id: "r1", label: "Communication", weight: 30 },
            { id: "r2", label: "Technical Skills", weight: 50 },
            { id: "r3", label: "Problem Solving", weight: 20 },
          ],
        })
      );

      dispatch(
        addAuditLog({
          jobId: job.id,
          message: "Rubric generated by AI assistant",
        })
      );

      reply("I have generated a new evaluation rubric for this role.");
      return;
    }

    // 2️⃣ Shortlist Candidates
    if (text.includes("shortlist")) {
      job.candidates.forEach((c) => {
        if (c.score > 85) {
          dispatch(
            updateCandidateStage({
              jobId: job.id,
              candidateId: c.id,
              newStage: "Shortlisted",
            })
          );
        }
      });

      dispatch(
        addAuditLog({
          jobId: job.id,
          message: "Top candidates shortlisted by AI assistant",
        })
      );

      reply("Top candidates have been shortlisted.");
      return;
    }

    // 3️⃣ Schedule Interview
    if (text.includes("schedule")) {
      reply("Interview scheduling opened.");
      return;
    }

    reply("Sorry, I didn't understand that yet.");
  };

  const reply = (text) => {
    dispatch(setAssistantStatus("speaking"));

    dispatch(
      addMessage({
        sender: "assistant",
        text,
        time: new Date().toLocaleTimeString(),
      })
    );

    setTimeout(() => {
      dispatch(setAssistantStatus("idle"));
    }, 500);
  };

  return (
    <div className="fixed bottom-24 right-6 w-80 bg-white rounded-xl shadow-lg border flex flex-col">
      {/* Header */}
      <div className="p-3 border-b flex items-center justify-between">
        <div className="flex items-center gap-2">
          <AssistantAvatar status={assistant.status} />
          <span className="font-semibold">TalentSage AI</span>
        </div>
        <button onClick={() => dispatch(toggleAssistant())}>✖</button>
      </div>

      {/* Messages */}
      <div className="flex-1 p-3 overflow-y-auto space-y-2 text-sm">
        {assistant.messages.map((msg, i) => (
          <div
            key={i}
            className={`p-2 rounded ${
              msg.sender === "user"
                ? "bg-blue-100 text-right"
                : "bg-gray-100"
            }`}
          >
            <p>{msg.text}</p>
            <span className="text-xs text-gray-400">{msg.time}</span>
          </div>
        ))}
      </div>

      {/* Input */}
      <div className="p-3 border-t">
        <input
          placeholder="Ask TalentSage..."
          className="w-full border rounded px-2 py-1 text-sm"
          onKeyDown={(e) => {
            if (e.key === "Enter") {
              sendMessage(e.target.value);
              e.target.value = "";
            }
          }}
        />
      </div>
    </div>
  );
}